services:
  dk-perception:
    image: deankh/perception:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    container_name: dk-perception
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-developer
      - LIBGL_ALWAYS_INDIRECT=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/home/developer/workspace/src/dk-perception
      # - ../dk-ros2:home/developer/workspace/src/dk-ros2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    user: developer
